name: jdlangtranslator
version: 1.0
summary: jdLangTranslator
description: |
  A translator for .lang files.
base: core18
confinement: strict
grade: stable

parts:
  locales-launch:

  jdlangtranslator:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    source: .
    build-packages:
      - python3
      - python3-pyqt5
      - python3-pyqt5.qtopengl
      - python3-setuptools
      - python3-pip
    stage-packages:
      - python3
      - python3-pyqt5
      - python3-pyqt5.qtopengl

apps:
  jdlangtranslator:
    command: locales-launch desktop-launch $SNAP/bin/jdLangTranslator
    plugs:
      - desktop
      - desktop-legacy
      - home
      - opengl
      - removable-media
      - wayland
      - x11
